/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./hl.g
 *     -                            On : 2019-03-30 16:26:59
 *     -                for the parser : hlParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "hlParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   phlParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  phlParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->phlParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->phlParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   hlParserTokenNames[16+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "DEF",
        (pANTLR3_UINT8) "DOT",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 hlParser_defid_return
	defid    (phlParser ctx);
static 
 hlParser_expr_return
	expr    (phlParser ctx);
static 
 hlParser_multExpr_return
	multExpr    (phlParser ctx);
static 
 hlParser_atom_return
	atom    (phlParser ctx);
static 
 hlParser_code_block_return
	code_block    (phlParser ctx);
static 
 hlParser_stmt_return
	stmt    (phlParser ctx);
static 
 hlParser_block_return
	block    (phlParser ctx);
static 
 hlParser_prog_return
	prog    (phlParser ctx);
static void	hlParserFree(phlParser ctx);
static void     hlParserReset (phlParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "./hl.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new hlParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API phlParser
hlParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return hlParserNewSSD(instream, NULL);
}

/** \brief Create a new hlParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API phlParser
hlParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    phlParser ctx;	    /* Context structure we will build and return   */

    ctx	= (phlParser) ANTLR3_CALLOC(1, sizeof(hlParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in hlParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our hlParser interface
     */
    ctx->defid	= defid;
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->code_block	= code_block;
    ctx->stmt	= stmt;
    ctx->block	= block;
    ctx->prog	= prog;
    ctx->free			= hlParserFree;
    ctx->reset			= hlParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = hlParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
hlParserReset (phlParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 hlParserFree(phlParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return hlParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DEF_in_defid59  */
static	ANTLR3_BITWORD FOLLOW_DEF_in_defid59_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_DEF_in_defid59	= { FOLLOW_DEF_in_defid59_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_defid62  */
static	ANTLR3_BITWORD FOLLOW_ID_in_defid62_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020080) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_defid62	= { FOLLOW_ID_in_defid62_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DOT_in_defid65  */
static	ANTLR3_BITWORD FOLLOW_DOT_in_defid65_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_DOT_in_defid65	= { FOLLOW_DOT_in_defid65_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_defid68  */
static	ANTLR3_BITWORD FOLLOW_ID_in_defid68_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020080) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_defid68	= { FOLLOW_ID_in_defid68_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_defid72  */
static	ANTLR3_BITWORD FOLLOW_17_in_defid72_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_defid72	= { FOLLOW_17_in_defid72_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr85  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr85_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr85	= { FOLLOW_multExpr_in_expr85_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr89  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr89_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr89	= { FOLLOW_PLUS_in_expr89_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr94  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr94_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr94	= { FOLLOW_MINUS_in_expr94_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr98  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr98_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr98	= { FOLLOW_multExpr_in_expr98_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr117  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr117_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr117	= { FOLLOW_atom_in_multExpr117_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multExpr120  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multExpr120_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multExpr120	= { FOLLOW_TIMES_in_multExpr120_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr123  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr123	= { FOLLOW_atom_in_multExpr123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom137  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom137_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom137	= { FOLLOW_INT_in_atom137_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom145  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom145_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom145	= { FOLLOW_ID_in_atom145_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_atom153  */
static	ANTLR3_BITWORD FOLLOW_15_in_atom153_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_atom153	= { FOLLOW_15_in_atom153_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom156  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom156	= { FOLLOW_expr_in_atom156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_atom158  */
static	ANTLR3_BITWORD FOLLOW_16_in_atom158_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_atom158	= { FOLLOW_16_in_atom158_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_code_block175  */
static	ANTLR3_BITWORD FOLLOW_18_in_code_block175_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000048B40) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_code_block175	= { FOLLOW_18_in_code_block175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_code_block179  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_code_block179_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C8B40) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_code_block179	= { FOLLOW_stmt_in_code_block179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_code_block183  */
static	ANTLR3_BITWORD FOLLOW_block_in_code_block183_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000C8B40) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_code_block183	= { FOLLOW_block_in_code_block183_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_code_block187  */
static	ANTLR3_BITWORD FOLLOW_19_in_code_block187_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_code_block187	= { FOLLOW_19_in_code_block187_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt200  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt200	= { FOLLOW_expr_in_stmt200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_stmt202  */
static	ANTLR3_BITWORD FOLLOW_17_in_stmt202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_stmt202	= { FOLLOW_17_in_stmt202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt204  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt204_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt204	= { FOLLOW_NEWLINE_in_stmt204_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_defid_in_stmt217  */
static	ANTLR3_BITWORD FOLLOW_defid_in_stmt217_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_defid_in_stmt217	= { FOLLOW_defid_in_stmt217_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt219  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt219_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt219	= { FOLLOW_NEWLINE_in_stmt219_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt235  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt235_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt235	= { FOLLOW_ID_in_stmt235_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt237  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt237_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt237	= { FOLLOW_ASSIGN_in_stmt237_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt239  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt239_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt239	= { FOLLOW_expr_in_stmt239_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_stmt241  */
static	ANTLR3_BITWORD FOLLOW_17_in_stmt241_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_stmt241	= { FOLLOW_17_in_stmt241_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt243  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt243_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt243	= { FOLLOW_NEWLINE_in_stmt243_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt262  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt262_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt262	= { FOLLOW_NEWLINE_in_stmt262_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_code_block_in_block283  */
static	ANTLR3_BITWORD FOLLOW_code_block_in_block283_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_code_block_in_block283	= { FOLLOW_code_block_in_block283_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_prog309  */
static	ANTLR3_BITWORD FOLLOW_block_in_prog309_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_prog309	= { FOLLOW_block_in_prog309_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start defid
 * ./hl.g:16:1: defid : DEF ! ID ( ',' ! ID )* ';' !;
 */
static hlParser_defid_return
defid(phlParser ctx)
{
    hlParser_defid_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    DEF1;
    pANTLR3_COMMON_TOKEN    ID2;
    pANTLR3_COMMON_TOKEN    char_literal3;
    pANTLR3_COMMON_TOKEN    ID4;
    pANTLR3_COMMON_TOKEN    char_literal5;

    pANTLR3_BASE_TREE DEF1_tree;
    pANTLR3_BASE_TREE ID2_tree;
    pANTLR3_BASE_TREE char_literal3_tree;
    pANTLR3_BASE_TREE ID4_tree;
    pANTLR3_BASE_TREE char_literal5_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    DEF1       = NULL;
    ID2       = NULL;
    char_literal3       = NULL;
    ID4       = NULL;
    char_literal5       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    DEF1_tree   = NULL;
    ID2_tree   = NULL;
    char_literal3_tree   = NULL;
    ID4_tree   = NULL;
    char_literal5_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./hl.g:17:5: ( DEF ! ID ( ',' ! ID )* ';' !)
        // ./hl.g:17:7: DEF ! ID ( ',' ! ID )* ';' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            DEF1 = (pANTLR3_COMMON_TOKEN) MATCHT(DEF, &FOLLOW_DEF_in_defid59);
            if  (HASEXCEPTION())
            {
                goto ruledefidEx;
            }


            ID2 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_defid62);
            if  (HASEXCEPTION())
            {
                goto ruledefidEx;
            }

            ID2_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID2));
            ADAPTOR->addChild(ADAPTOR, root_0, ID2_tree);


            // ./hl.g:17:15: ( ',' ! ID )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case DOT:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // ./hl.g:17:16: ',' ! ID
            	    {
            	        char_literal3 = (pANTLR3_COMMON_TOKEN) MATCHT(DOT, &FOLLOW_DOT_in_defid65);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledefidEx;
            	        }


            	        ID4 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_defid68);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledefidEx;
            	        }

            	        ID4_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID4));
            	        ADAPTOR->addChild(ADAPTOR, root_0, ID4_tree);


            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


            char_literal5 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_defid72);
            if  (HASEXCEPTION())
            {
                goto ruledefidEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledefidEx; /* Prevent compiler warnings */
    ruledefidEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end defid */

/**
 * $ANTLR start expr
 * ./hl.g:20:1: expr : multExpr ( ( PLUS ^| MINUS ^) multExpr )* ;
 */
static hlParser_expr_return
expr(phlParser ctx)
{
    hlParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS7;
    pANTLR3_COMMON_TOKEN    MINUS8;
    hlParser_multExpr_return multExpr6;
    #undef	RETURN_TYPE_multExpr6
    #define	RETURN_TYPE_multExpr6 hlParser_multExpr_return

    hlParser_multExpr_return multExpr9;
    #undef	RETURN_TYPE_multExpr9
    #define	RETURN_TYPE_multExpr9 hlParser_multExpr_return

    pANTLR3_BASE_TREE PLUS7_tree;
    pANTLR3_BASE_TREE MINUS8_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS7       = NULL;
    MINUS8       = NULL;
    multExpr6.tree = NULL;

    multExpr9.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS7_tree   = NULL;
    MINUS8_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./hl.g:20:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* )
        // ./hl.g:20:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_expr85);
            multExpr6=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr6.tree);

            // ./hl.g:20:16: ( ( PLUS ^| MINUS ^) multExpr )*

            for (;;)
            {
                int alt3=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt3=1;
                	}
                    break;

                }

                switch (alt3)
                {
            	case 1:
            	    // ./hl.g:20:17: ( PLUS ^| MINUS ^) multExpr
            	    {
            	        // ./hl.g:20:17: ( PLUS ^| MINUS ^)
            	        {
            	            int alt2=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt2=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt2=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 2;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt2)
            	            {
            	        	case 1:
            	        	    // ./hl.g:20:18: PLUS ^
            	        	    {
            	        	        PLUS7 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr89);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        PLUS7_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS7))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS7_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ./hl.g:20:26: MINUS ^
            	        	    {
            	        	        MINUS8 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr94);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        MINUS8_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS8))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS8_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_expr98);
            	        multExpr9=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr9.tree);

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * ./hl.g:23:1: multExpr : atom ( TIMES ^ atom )* ;
 */
static hlParser_multExpr_return
multExpr(phlParser ctx)
{
    hlParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES11;
    hlParser_atom_return atom10;
    #undef	RETURN_TYPE_atom10
    #define	RETURN_TYPE_atom10 hlParser_atom_return

    hlParser_atom_return atom12;
    #undef	RETURN_TYPE_atom12
    #define	RETURN_TYPE_atom12 hlParser_atom_return

    pANTLR3_BASE_TREE TIMES11_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES11       = NULL;
    atom10.tree = NULL;

    atom12.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES11_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./hl.g:24:5: ( atom ( TIMES ^ atom )* )
        // ./hl.g:24:7: atom ( TIMES ^ atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr117);
            atom10=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom10.tree);

            // ./hl.g:24:12: ( TIMES ^ atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ./hl.g:24:13: TIMES ^ atom
            	    {
            	        TIMES11 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multExpr120);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        TIMES11_tree = 
            	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES11))
            	        ;
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES11_tree, root_0));


            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr123);
            	        atom12=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom12.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * ./hl.g:27:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static hlParser_atom_return
atom(phlParser ctx)
{
    hlParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT13;
    pANTLR3_COMMON_TOKEN    ID14;
    pANTLR3_COMMON_TOKEN    char_literal15;
    pANTLR3_COMMON_TOKEN    char_literal17;
    hlParser_expr_return expr16;
    #undef	RETURN_TYPE_expr16
    #define	RETURN_TYPE_expr16 hlParser_expr_return

    pANTLR3_BASE_TREE INT13_tree;
    pANTLR3_BASE_TREE ID14_tree;
    pANTLR3_BASE_TREE char_literal15_tree;
    pANTLR3_BASE_TREE char_literal17_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT13       = NULL;
    ID14       = NULL;
    char_literal15       = NULL;
    char_literal17       = NULL;
    expr16.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT13_tree   = NULL;
    ID14_tree   = NULL;
    char_literal15_tree   = NULL;
    char_literal17_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ./hl.g:27:5: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt5;

            alt5=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt5=1;
            	}
                break;
            case ID:
            	{
            		alt5=2;
            	}
                break;
            case 15:
            	{
            		alt5=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt5)
            {
        	case 1:
        	    // ./hl.g:27:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT13 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom137);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT13_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT13));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT13_tree);


        	    }
        	    break;
        	case 2:
        	    // ./hl.g:28:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID14 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom145);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID14_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID14));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID14_tree);


        	    }
        	    break;
        	case 3:
        	    // ./hl.g:29:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal15 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_atom153);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom156);
        	        expr16=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr16.tree);

        	        char_literal17 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_atom158);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start code_block
 * ./hl.g:32:1: code_block : '{' ! ( stmt | block )+ '}' !;
 */
static hlParser_code_block_return
code_block(phlParser ctx)
{
    hlParser_code_block_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal18;
    pANTLR3_COMMON_TOKEN    char_literal21;
    hlParser_stmt_return stmt19;
    #undef	RETURN_TYPE_stmt19
    #define	RETURN_TYPE_stmt19 hlParser_stmt_return

    hlParser_block_return block20;
    #undef	RETURN_TYPE_block20
    #define	RETURN_TYPE_block20 hlParser_block_return

    pANTLR3_BASE_TREE char_literal18_tree;
    pANTLR3_BASE_TREE char_literal21_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal18       = NULL;
    char_literal21       = NULL;
    stmt19.tree = NULL;

    block20.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal18_tree   = NULL;
    char_literal21_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./hl.g:32:11: ( '{' ! ( stmt | block )+ '}' !)
        // ./hl.g:33:5: '{' ! ( stmt | block )+ '}' !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            char_literal18 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_code_block175);
            if  (HASEXCEPTION())
            {
                goto rulecode_blockEx;
            }


            // ./hl.g:33:10: ( stmt | block )+
            {
                int cnt6=0;

                for (;;)
                {
                    int alt6=3;
            	switch ( LA(1) )
            	{
            	case DEF:
            	case ID:
            	case INT:
            	case NEWLINE:
            	case 15:
            		{
            			alt6=1;
            		}
            	    break;
            	case 18:
            		{
            			alt6=2;
            		}
            	    break;

            	}

            	switch (alt6)
            	{
            	    case 1:
            	        // ./hl.g:33:11: stmt
            	        {
            	            FOLLOWPUSH(FOLLOW_stmt_in_code_block179);
            	            stmt19=stmt(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulecode_blockEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, stmt19.tree);

            	        }
            	        break;
            	    case 2:
            	        // ./hl.g:33:18: block
            	        {
            	            FOLLOWPUSH(FOLLOW_block_in_code_block183);
            	            block20=block(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulecode_blockEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, block20.tree);

            	        }
            	        break;

            	    default:

            		if ( cnt6 >= 1 )
            		{
            		    goto loop6;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulecode_blockEx;
            	}
            	cnt6++;
                }
                loop6: ;	/* Jump to here if this rule does not match */
            }

            char_literal21 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_code_block187);
            if  (HASEXCEPTION())
            {
                goto rulecode_blockEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulecode_blockEx; /* Prevent compiler warnings */
    rulecode_blockEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end code_block */

/**
 * $ANTLR start stmt
 * ./hl.g:36:1: stmt : ( expr ';' NEWLINE -> expr | defid NEWLINE -> ^( DEF defid ) | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | NEWLINE ->);
 */
static hlParser_stmt_return
stmt(phlParser ctx)
{
    hlParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal23;
    pANTLR3_COMMON_TOKEN    NEWLINE24;
    pANTLR3_COMMON_TOKEN    NEWLINE26;
    pANTLR3_COMMON_TOKEN    ID27;
    pANTLR3_COMMON_TOKEN    ASSIGN28;
    pANTLR3_COMMON_TOKEN    char_literal30;
    pANTLR3_COMMON_TOKEN    NEWLINE31;
    pANTLR3_COMMON_TOKEN    NEWLINE32;
    hlParser_expr_return expr22;
    #undef	RETURN_TYPE_expr22
    #define	RETURN_TYPE_expr22 hlParser_expr_return

    hlParser_defid_return defid25;
    #undef	RETURN_TYPE_defid25
    #define	RETURN_TYPE_defid25 hlParser_defid_return

    hlParser_expr_return expr29;
    #undef	RETURN_TYPE_expr29
    #define	RETURN_TYPE_expr29 hlParser_expr_return

    pANTLR3_BASE_TREE char_literal23_tree;
    pANTLR3_BASE_TREE NEWLINE24_tree;
    pANTLR3_BASE_TREE NEWLINE26_tree;
    pANTLR3_BASE_TREE ID27_tree;
    pANTLR3_BASE_TREE ASSIGN28_tree;
    pANTLR3_BASE_TREE char_literal30_tree;
    pANTLR3_BASE_TREE NEWLINE31_tree;
    pANTLR3_BASE_TREE NEWLINE32_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_17;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_defid;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal23       = NULL;
    NEWLINE24       = NULL;
    NEWLINE26       = NULL;
    ID27       = NULL;
    ASSIGN28       = NULL;
    char_literal30       = NULL;
    NEWLINE31       = NULL;
    NEWLINE32       = NULL;
    expr22.tree = NULL;

    defid25.tree = NULL;

    expr29.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal23_tree   = NULL;
    NEWLINE24_tree   = NULL;
    NEWLINE26_tree   = NULL;
    ID27_tree   = NULL;
    ASSIGN28_tree   = NULL;
    char_literal30_tree   = NULL;
    NEWLINE31_tree   = NULL;
    NEWLINE32_tree   = NULL;

    stream_17   = NULL;
    #define CREATE_stream_17  if (stream_17 == NULL) {stream_17 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 17"); } 
    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_defid   = NULL;
    #define CREATE_stream_defid  if (stream_defid == NULL) {stream_defid = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule defid"); }
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ./hl.g:36:5: ( expr ';' NEWLINE -> expr | defid NEWLINE -> ^( DEF defid ) | ID ASSIGN expr ';' NEWLINE -> ^( ASSIGN ID expr ) | NEWLINE ->)

            ANTLR3_UINT32 alt7;

            alt7=4;

            switch ( LA(1) )
            {
            case INT:
            case 15:
            	{
            		alt7=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt7=3;
            			}
            		    break;
            		case MINUS:
            		case PLUS:
            		case TIMES:
            		case 17:
            			{
            				alt7=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 7;
            		    EXCEPTION->state        = 2;


            		    goto rulestmtEx;

            		}

            	}
                break;
            case DEF:
            	{
            		alt7=2;
            	}
                break;
            case NEWLINE:
            	{
            		alt7=4;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // ./hl.g:36:7: expr ';' NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stmt200);
        	        expr22=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr22.tree, NULL);

        	        char_literal23 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_stmt202);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_17; stream_17->add(stream_17, char_literal23, NULL);


        	        NEWLINE24 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt204);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE24, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 36:24: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // ./hl.g:37:7: defid NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_defid_in_stmt217);
        	        defid25=defid(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_defid; stream_defid->add(stream_defid, defid25.tree, NULL);

        	        NEWLINE26 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt219);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE26, NULL);


        	        /* AST REWRITE
        	         * elements          : defid
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 37:21: -> ^( DEF defid )
        	        	{
        	        	    // ./hl.g:37:24: ^( DEF defid )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, DEF, (pANTLR3_UINT8)"DEF")
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_defid == NULL ? NULL : stream_defid->nextTree(stream_defid));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // ./hl.g:38:7: ID ASSIGN expr ';' NEWLINE
        	    {
        	        ID27 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt235);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID27, NULL);


        	        ASSIGN28 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt237);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN28, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt239);
        	        expr29=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr29.tree, NULL);

        	        char_literal30 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_stmt241);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_17; stream_17->add(stream_17, char_literal30, NULL);


        	        NEWLINE31 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt243);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE31, NULL);


        	        /* AST REWRITE
        	         * elements          : ID, ASSIGN, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 38:34: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ./hl.g:38:37: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 4:
        	    // ./hl.g:39:7: NEWLINE
        	    {
        	        NEWLINE32 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt262);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE32, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 39:15: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_17 != NULL) stream_17->free(stream_17);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_defid != NULL) stream_defid->free(stream_defid);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start block
 * ./hl.g:42:1: block : code_block -> ^( BLOCK code_block ) ;
 */
static hlParser_block_return
block(phlParser ctx)
{
    hlParser_block_return retval;


    pANTLR3_BASE_TREE root_0;

    hlParser_code_block_return code_block33;
    #undef	RETURN_TYPE_code_block33
    #define	RETURN_TYPE_code_block33 hlParser_code_block_return

    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_code_block;
    /* Initialize rule variables
     */

    root_0 = NULL;

    code_block33.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;



    stream_code_block   = NULL;
    #define CREATE_stream_code_block  if (stream_code_block == NULL) {stream_code_block = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule code_block"); }

    retval.tree  = NULL;

    {
        // ./hl.g:42:6: ( code_block -> ^( BLOCK code_block ) )
        // ./hl.g:43:5: code_block
        {
            FOLLOWPUSH(FOLLOW_code_block_in_block283);
            code_block33=code_block(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }

            CREATE_stream_code_block; stream_code_block->add(stream_code_block, code_block33.tree, NULL);

            /* AST REWRITE
             * elements          : code_block
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 43:16: -> ^( BLOCK code_block )
            	{
            	    // ./hl.g:43:19: ^( BLOCK code_block )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_code_block == NULL ? NULL : stream_code_block->nextTree(stream_code_block));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblockEx; /* Prevent compiler warnings */
    ruleblockEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_code_block != NULL) stream_code_block->free(stream_code_block);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block */

/**
 * $ANTLR start prog
 * ./hl.g:46:1: prog : ( block )+ ;
 */
static hlParser_prog_return
prog(phlParser ctx)
{
    hlParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    hlParser_block_return block34;
    #undef	RETURN_TYPE_block34
    #define	RETURN_TYPE_block34 hlParser_block_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    block34.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ./hl.g:47:5: ( ( block )+ )
        // ./hl.g:47:7: ( block )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ./hl.g:47:7: ( block )+
            {
                int cnt8=0;

                for (;;)
                {
                    int alt8=2;
            	switch ( LA(1) )
            	{
            	case 18:
            		{
            			alt8=1;
            		}
            	    break;

            	}

            	switch (alt8)
            	{
            	    case 1:
            	        // ./hl.g:47:8: block
            	        {
            	            FOLLOWPUSH(FOLLOW_block_in_prog309);
            	            block34=block(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, block34.tree);

            	            {

            	                            pANTLR3_STRING s = (block34.tree)->toStringTree((block34.tree));
            	                            assert(s->chars);
            	                            printf("tree %s\n", s->chars);
            	                    
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt8 >= 1 )
            		{
            		    goto loop8;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt8++;
                }
                loop8: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
