/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ExprCppTree.g
 *     -                            On : 2019-03-15 09:10:28
 *     -                for the parser : ExprCppTreeParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ExprCppTreeParserTokenNames[11+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ExprCppTreeParser_expr_return
	expr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_plus_minusExpr_return
	plus_minusExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_multExpr_return
	multExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_atom_return
	atom    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_stmt_return
	stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_prog_return
	prog    (pExprCppTreeParser ctx);
static void	ExprCppTreeParserFree(pExprCppTreeParser ctx);
static void     ExprCppTreeParserReset (pExprCppTreeParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ExprCppTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pExprCppTreeParser) ANTLR3_CALLOC(1, sizeof(ExprCppTreeParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ExprCppTreeParser interface
     */
    ctx->expr	= expr;
    ctx->plus_minusExpr	= plus_minusExpr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->stmt	= stmt;
    ctx->prog	= prog;
    ctx->free			= ExprCppTreeParserFree;
    ctx->reset			= ExprCppTreeParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ExprCppTreeParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ExprCppTreeParserReset (pExprCppTreeParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ExprCppTreeParserFree(pExprCppTreeParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ExprCppTreeParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_plus_minusExpr_in_expr50  */
static	ANTLR3_BITWORD FOLLOW_plus_minusExpr_in_expr50_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000022) };
static  ANTLR3_BITSET_LIST FOLLOW_plus_minusExpr_in_expr50	= { FOLLOW_plus_minusExpr_in_expr50_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_expr53  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_expr53_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002080) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_expr53	= { FOLLOW_COMMA_in_expr53_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_plus_minusExpr_in_expr56  */
static	ANTLR3_BITWORD FOLLOW_plus_minusExpr_in_expr56_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000022) };
static  ANTLR3_BITSET_LIST FOLLOW_plus_minusExpr_in_expr56	= { FOLLOW_plus_minusExpr_in_expr56_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_plus_minusExpr88  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_plus_minusExpr88_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000502) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_plus_minusExpr88	= { FOLLOW_multExpr_in_plus_minusExpr88_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_plus_minusExpr92  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_plus_minusExpr92_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002080) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_plus_minusExpr92	= { FOLLOW_PLUS_in_plus_minusExpr92_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_plus_minusExpr97  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_plus_minusExpr97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002080) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_plus_minusExpr97	= { FOLLOW_MINUS_in_plus_minusExpr97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_plus_minusExpr101  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_plus_minusExpr101_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000502) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_plus_minusExpr101	= { FOLLOW_multExpr_in_plus_minusExpr101_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr120  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr120_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr120	= { FOLLOW_atom_in_multExpr120_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multExpr123  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multExpr123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002080) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multExpr123	= { FOLLOW_TIMES_in_multExpr123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr126  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr126_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr126	= { FOLLOW_atom_in_multExpr126_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom153  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom153_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom153	= { FOLLOW_INT_in_atom153_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_atom161  */
static	ANTLR3_BITWORD FOLLOW_13_in_atom161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_atom161	= { FOLLOW_13_in_atom161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom164  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom164_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom164	= { FOLLOW_ID_in_atom164_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_atom167  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_atom167_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_atom167	= { FOLLOW_ASSIGN_in_atom167_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom170  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom170_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004010) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom170	= { FOLLOW_INT_in_atom170_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_atom174  */
static	ANTLR3_BITWORD FOLLOW_14_in_atom174_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_atom174	= { FOLLOW_14_in_atom174_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_atom183  */
static	ANTLR3_BITWORD FOLLOW_13_in_atom183_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002080) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_atom183	= { FOLLOW_13_in_atom183_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom186  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom186_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom186	= { FOLLOW_expr_in_atom186_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_atom188  */
static	ANTLR3_BITWORD FOLLOW_14_in_atom188_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_atom188	= { FOLLOW_14_in_atom188_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt201  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt201_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt201	= { FOLLOW_expr_in_stmt201_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt203  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt203_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt203	= { FOLLOW_NEWLINE_in_stmt203_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt217  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt217_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt217	= { FOLLOW_ID_in_stmt217_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt219  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt219_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002080) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt219	= { FOLLOW_ASSIGN_in_stmt219_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt221  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt221_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt221	= { FOLLOW_expr_in_stmt221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt223  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt223_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt223	= { FOLLOW_NEWLINE_in_stmt223_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt242  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt242_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt242	= { FOLLOW_NEWLINE_in_stmt242_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_prog270  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_prog270_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000022C2) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_prog270	= { FOLLOW_stmt_in_prog270_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * ExprCppTree.g:12:1: expr : plus_minusExpr ( COMMA ^ plus_minusExpr )* ;
 */
static ExprCppTreeParser_expr_return
expr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    COMMA2;
    ExprCppTreeParser_plus_minusExpr_return plus_minusExpr1;
    #undef	RETURN_TYPE_plus_minusExpr1
    #define	RETURN_TYPE_plus_minusExpr1 ExprCppTreeParser_plus_minusExpr_return

    ExprCppTreeParser_plus_minusExpr_return plus_minusExpr3;
    #undef	RETURN_TYPE_plus_minusExpr3
    #define	RETURN_TYPE_plus_minusExpr3 ExprCppTreeParser_plus_minusExpr_return

    pANTLR3_BASE_TREE COMMA2_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    COMMA2       = NULL;
    plus_minusExpr1.tree = NULL;

    plus_minusExpr3.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    COMMA2_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:12:5: ( plus_minusExpr ( COMMA ^ plus_minusExpr )* )
        // ExprCppTree.g:12:7: plus_minusExpr ( COMMA ^ plus_minusExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_plus_minusExpr_in_expr50);
            plus_minusExpr1=plus_minusExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, plus_minusExpr1.tree);

            // ExprCppTree.g:12:22: ( COMMA ^ plus_minusExpr )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case COMMA:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // ExprCppTree.g:12:23: COMMA ^ plus_minusExpr
            	    {
            	        COMMA2 = (pANTLR3_COMMON_TOKEN) MATCHT(COMMA, &FOLLOW_COMMA_in_expr53);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        COMMA2_tree = 
            	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, COMMA2))
            	        ;
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, COMMA2_tree, root_0));


            	        FOLLOWPUSH(FOLLOW_plus_minusExpr_in_expr56);
            	        plus_minusExpr3=plus_minusExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, plus_minusExpr3.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start plus_minusExpr
 * ExprCppTree.g:17:1: plus_minusExpr : multExpr ( ( PLUS ^| MINUS ^) multExpr )* ;
 */
static ExprCppTreeParser_plus_minusExpr_return
plus_minusExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_plus_minusExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS5;
    pANTLR3_COMMON_TOKEN    MINUS6;
    ExprCppTreeParser_multExpr_return multExpr4;
    #undef	RETURN_TYPE_multExpr4
    #define	RETURN_TYPE_multExpr4 ExprCppTreeParser_multExpr_return

    ExprCppTreeParser_multExpr_return multExpr7;
    #undef	RETURN_TYPE_multExpr7
    #define	RETURN_TYPE_multExpr7 ExprCppTreeParser_multExpr_return

    pANTLR3_BASE_TREE PLUS5_tree;
    pANTLR3_BASE_TREE MINUS6_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS5       = NULL;
    MINUS6       = NULL;
    multExpr4.tree = NULL;

    multExpr7.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS5_tree   = NULL;
    MINUS6_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:18:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* )
        // ExprCppTree.g:18:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_plus_minusExpr88);
            multExpr4=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleplus_minusExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr4.tree);

            // ExprCppTree.g:18:16: ( ( PLUS ^| MINUS ^) multExpr )*

            for (;;)
            {
                int alt3=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt3=1;
                	}
                    break;

                }

                switch (alt3)
                {
            	case 1:
            	    // ExprCppTree.g:18:17: ( PLUS ^| MINUS ^) multExpr
            	    {
            	        // ExprCppTree.g:18:17: ( PLUS ^| MINUS ^)
            	        {
            	            int alt2=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt2=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt2=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 2;
            	                EXCEPTION->state        = 0;


            	                goto ruleplus_minusExprEx;

            	            }

            	            switch (alt2)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:18:18: PLUS ^
            	        	    {
            	        	        PLUS5 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_plus_minusExpr92);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleplus_minusExprEx;
            	        	        }

            	        	        PLUS5_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS5))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS5_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:18:26: MINUS ^
            	        	    {
            	        	        MINUS6 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_plus_minusExpr97);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleplus_minusExprEx;
            	        	        }

            	        	        MINUS6_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS6))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS6_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_plus_minusExpr101);
            	        multExpr7=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleplus_minusExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr7.tree);

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleplus_minusExprEx; /* Prevent compiler warnings */
    ruleplus_minusExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end plus_minusExpr */

/**
 * $ANTLR start multExpr
 * ExprCppTree.g:21:1: multExpr : atom ( TIMES ^ atom )* ;
 */
static ExprCppTreeParser_multExpr_return
multExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES9;
    ExprCppTreeParser_atom_return atom8;
    #undef	RETURN_TYPE_atom8
    #define	RETURN_TYPE_atom8 ExprCppTreeParser_atom_return

    ExprCppTreeParser_atom_return atom10;
    #undef	RETURN_TYPE_atom10
    #define	RETURN_TYPE_atom10 ExprCppTreeParser_atom_return

    pANTLR3_BASE_TREE TIMES9_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES9       = NULL;
    atom8.tree = NULL;

    atom10.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES9_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:22:5: ( atom ( TIMES ^ atom )* )
        // ExprCppTree.g:22:7: atom ( TIMES ^ atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr120);
            atom8=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom8.tree);

            // ExprCppTree.g:22:12: ( TIMES ^ atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ExprCppTree.g:22:13: TIMES ^ atom
            	    {
            	        TIMES9 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multExpr123);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        TIMES9_tree = 
            	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES9))
            	        ;
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES9_tree, root_0));


            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr126);
            	        atom10=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom10.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * ExprCppTree.g:28:1: atom : ( INT | '(' ! ID ( ASSIGN ^ INT )* ')' !| '(' ! expr ')' !);
 */
static ExprCppTreeParser_atom_return
atom(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT11;
    pANTLR3_COMMON_TOKEN    char_literal12;
    pANTLR3_COMMON_TOKEN    ID13;
    pANTLR3_COMMON_TOKEN    ASSIGN14;
    pANTLR3_COMMON_TOKEN    INT15;
    pANTLR3_COMMON_TOKEN    char_literal16;
    pANTLR3_COMMON_TOKEN    char_literal17;
    pANTLR3_COMMON_TOKEN    char_literal19;
    ExprCppTreeParser_expr_return expr18;
    #undef	RETURN_TYPE_expr18
    #define	RETURN_TYPE_expr18 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE INT11_tree;
    pANTLR3_BASE_TREE char_literal12_tree;
    pANTLR3_BASE_TREE ID13_tree;
    pANTLR3_BASE_TREE ASSIGN14_tree;
    pANTLR3_BASE_TREE INT15_tree;
    pANTLR3_BASE_TREE char_literal16_tree;
    pANTLR3_BASE_TREE char_literal17_tree;
    pANTLR3_BASE_TREE char_literal19_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT11       = NULL;
    char_literal12       = NULL;
    ID13       = NULL;
    ASSIGN14       = NULL;
    INT15       = NULL;
    char_literal16       = NULL;
    char_literal17       = NULL;
    char_literal19       = NULL;
    expr18.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT11_tree   = NULL;
    char_literal12_tree   = NULL;
    ID13_tree   = NULL;
    ASSIGN14_tree   = NULL;
    INT15_tree   = NULL;
    char_literal16_tree   = NULL;
    char_literal17_tree   = NULL;
    char_literal19_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:28:5: ( INT | '(' ! ID ( ASSIGN ^ INT )* ')' !| '(' ! expr ')' !)

            ANTLR3_UINT32 alt6;

            alt6=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt6=1;
            	}
                break;
            case 13:
            	{
            		switch ( LA(2) )
            		{
            		case ID:
            			{
            				alt6=2;
            			}
            		    break;
            		case INT:
            		case 13:
            			{
            				alt6=3;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 6;
            		    EXCEPTION->state        = 2;


            		    goto ruleatomEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // ExprCppTree.g:28:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT11 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom153);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT11));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT11_tree);


        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:29:7: '(' ! ID ( ASSIGN ^ INT )* ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal12 = (pANTLR3_COMMON_TOKEN) MATCHT(13, &FOLLOW_13_in_atom161);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        ID13 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom164);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID13_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID13));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID13_tree);


        	        // ExprCppTree.g:29:15: ( ASSIGN ^ INT )*

        	        for (;;)
        	        {
        	            int alt5=2;
        	            switch ( LA(1) )
        	            {
        	            case ASSIGN:
        	            	{
        	            		alt5=1;
        	            	}
        	                break;

        	            }

        	            switch (alt5)
        	            {
        	        	case 1:
        	        	    // ExprCppTree.g:29:16: ASSIGN ^ INT
        	        	    {
        	        	        ASSIGN14 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_atom167);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleatomEx;
        	        	        }

        	        	        ASSIGN14_tree = 
        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ASSIGN14))
        	        	        ;
        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ASSIGN14_tree, root_0));


        	        	        INT15 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom170);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleatomEx;
        	        	        }

        	        	        INT15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT15));
        	        	        ADAPTOR->addChild(ADAPTOR, root_0, INT15_tree);


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop5;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop5: ; /* Jump out to here if this rule does not match */


        	        char_literal16 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_atom174);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:30:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal17 = (pANTLR3_COMMON_TOKEN) MATCHT(13, &FOLLOW_13_in_atom183);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom186);
        	        expr18=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr18.tree);

        	        char_literal19 = (pANTLR3_COMMON_TOKEN) MATCHT(14, &FOLLOW_14_in_atom188);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start stmt
 * ExprCppTree.g:33:1: stmt : ( expr NEWLINE -> expr | ID ASSIGN expr NEWLINE -> ^( ASSIGN ID expr ) | NEWLINE ->);
 */
static ExprCppTreeParser_stmt_return
stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NEWLINE21;
    pANTLR3_COMMON_TOKEN    ID22;
    pANTLR3_COMMON_TOKEN    ASSIGN23;
    pANTLR3_COMMON_TOKEN    NEWLINE25;
    pANTLR3_COMMON_TOKEN    NEWLINE26;
    ExprCppTreeParser_expr_return expr20;
    #undef	RETURN_TYPE_expr20
    #define	RETURN_TYPE_expr20 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr24;
    #undef	RETURN_TYPE_expr24
    #define	RETURN_TYPE_expr24 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE NEWLINE21_tree;
    pANTLR3_BASE_TREE ID22_tree;
    pANTLR3_BASE_TREE ASSIGN23_tree;
    pANTLR3_BASE_TREE NEWLINE25_tree;
    pANTLR3_BASE_TREE NEWLINE26_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    NEWLINE21       = NULL;
    ID22       = NULL;
    ASSIGN23       = NULL;
    NEWLINE25       = NULL;
    NEWLINE26       = NULL;
    expr20.tree = NULL;

    expr24.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    NEWLINE21_tree   = NULL;
    ID22_tree   = NULL;
    ASSIGN23_tree   = NULL;
    NEWLINE25_tree   = NULL;
    NEWLINE26_tree   = NULL;

    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:33:5: ( expr NEWLINE -> expr | ID ASSIGN expr NEWLINE -> ^( ASSIGN ID expr ) | NEWLINE ->)

            ANTLR3_UINT32 alt7;

            alt7=3;

            switch ( LA(1) )
            {
            case INT:
            case 13:
            	{
            		alt7=1;
            	}
                break;
            case ID:
            	{
            		alt7=2;
            	}
                break;
            case NEWLINE:
            	{
            		alt7=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // ExprCppTree.g:33:7: expr NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stmt201);
        	        expr20=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr20.tree, NULL);

        	        NEWLINE21 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt203);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE21, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 33:20: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:34:7: ID ASSIGN expr NEWLINE
        	    {
        	        ID22 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt217);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID22, NULL);


        	        ASSIGN23 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt219);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN23, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt221);
        	        expr24=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr24.tree, NULL);

        	        NEWLINE25 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt223);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE25, NULL);


        	        /* AST REWRITE
        	         * elements          : ID, ASSIGN, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 34:30: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ExprCppTree.g:34:33: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:35:7: NEWLINE
        	    {
        	        NEWLINE26 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt242);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE26, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 35:15: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start prog
 * ExprCppTree.g:38:1: prog : ( stmt )+ ;
 */
static ExprCppTreeParser_prog_return
prog(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt27;
    #undef	RETURN_TYPE_stmt27
    #define	RETURN_TYPE_stmt27 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt27.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:39:5: ( ( stmt )+ )
        // ExprCppTree.g:39:7: ( stmt )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:39:7: ( stmt )+
            {
                int cnt8=0;

                for (;;)
                {
                    int alt8=2;
            	switch ( LA(1) )
            	{
            	case ID:
            	case INT:
            	case NEWLINE:
            	case 13:
            		{
            			alt8=1;
            		}
            	    break;

            	}

            	switch (alt8)
            	{
            	    case 1:
            	        // ExprCppTree.g:39:8: stmt
            	        {
            	            FOLLOWPUSH(FOLLOW_stmt_in_prog270);
            	            stmt27=stmt(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, stmt27.tree);

            	            {
            	                pANTLR3_STRING s = (stmt27.tree)->toStringTree((stmt27.tree));
            	                             assert(s->chars);
            	                             printf("Haizei tree %s\n", s->chars);
            	                            
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt8 >= 1 )
            		{
            		    goto loop8;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt8++;
                }
                loop8: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
